
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10 * * * *' # 매 시간 10분에 실행

name: hello

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Install remotes
        run: Rscript -e 'install.packages("remotes")'
      
      - name: Install ntfy package
        run: Rscript -e 'remotes::install_github("jonocarroll/ntfy")'

      - name: Fetch latest data
        run:  Rscript hello.R
      
      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "<>"
          git commit -m '헬로월드' || exit 0
          git push origin
  
        