
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10 * * * *' # 매 시간 10분에 실행

name: nesdc

jobs:
  nesdc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NESDC_TOPIC: ${{ secrets.NESDC_TOPIC }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Fetch polls info
        run:  Rscript nesdc.R
      
      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "<>"
          git commit -m '신규 여론조사' || exit 0
          git push origin
          
